### ISSUE TITLE
Failed to HMR

### ISSUE THREAD

**Issue by ghost** [thomasthiebaud/react-kit#2]
I find that the react-kit boilerplate could not fully support hmr, Because I make some text changes to `Home/Home.js`. To my surprise, the html page  are not updated automatically. Namely, I need to manually refresh the html page. After several tries, I still fall into the above trap. Look forward to reply.

**Comment by thomasthiebaud** [comment]
Hej, I will have a look today and see if I can fix it

**Comment by ghost** [comment]
Thanks for your reply. But after several tries, the above issue has already been resolved. That is to say, I has done one thing to upgrade react hot loader to v4. To my surprise, it worked. Not sure if the solution is suitable for you.

**Comment by thomasthiebaud** [comment]
Yes it is, I'm working on a new major version (https://github.com/thomasthiebaud/react-kit/tree/major-refactor). I also upgraded to `react-hot-loader v4` and it solved the issue. It should be merged soon

**Comment by thomasthiebaud** [comment]
Should be fix in master now. I close the issue.
